// Country to currency mapping
const countryCurrencyMap: Record<string, string> = {
  'United States': 'USD',
  'India': 'INR',
  'United Kingdom': 'GBP',
  'Canada': 'CAD',
  'Australia': 'AUD',
  'Germany': 'EUR',
  'France': 'EUR',
  'Spain': 'EUR',
  'Italy': 'EUR',
  'Japan': 'JPY',
  'China': 'CNY',
  'Brazil': 'BRL',
  'Mexico': 'MXN',
  'Singapore': 'SGD',
  'Switzerland': 'CHF',
  'South Korea': 'KRW',
  'Russia': 'RUB',
  'South Africa': 'ZAR',
  'New Zealand': 'NZD',
  'Sweden': 'SEK',
  'Norway': 'NOK',
  'Denmark': 'DKK',
  'Poland': 'PLN',
  'Turkey': 'TRY',
  'Indonesia': 'IDR',
  'Malaysia': 'MYR',
  'Thailand': 'THB',
  'Philippines': 'PHP',
  'Vietnam': 'VND',
  'Argentina': 'ARS',
  'Chile': 'CLP',
  'Colombia': 'COP',
  'Peru': 'PEN',
  'UAE': 'AED',
  'Saudi Arabia': 'SAR',
  'Israel': 'ILS',
  'Egypt': 'EGP',
  'Nigeria': 'NGN',
  'Kenya': 'KES',
  'Pakistan': 'PKR',
  'Bangladesh': 'BDT',
  'Sri Lanka': 'LKR',
};

// Country to locale mapping
const countryLocaleMap: Record<string, string> = {
  'United States': 'en-US',
  'India': 'en-IN',
  'United Kingdom': 'en-GB',
  'Canada': 'en-CA',
  'Australia': 'en-AU',
  'Germany': 'de-DE',
  'France': 'fr-FR',
  'Spain': 'es-ES',
  'Italy': 'it-IT',
  'Japan': 'ja-JP',
  'China': 'zh-CN',
  'Brazil': 'pt-BR',
  'Mexico': 'es-MX',
  'Singapore': 'en-SG',
  'Switzerland': 'de-CH',
  'South Korea': 'ko-KR',
  'Russia': 'ru-RU',
  'South Africa': 'en-ZA',
  'New Zealand': 'en-NZ',
  'Sweden': 'sv-SE',
  'Norway': 'nb-NO',
  'Denmark': 'da-DK',
  'Poland': 'pl-PL',
  'Turkey': 'tr-TR',
  'Indonesia': 'id-ID',
  'Malaysia': 'ms-MY',
  'Thailand': 'th-TH',
  'Philippines': 'en-PH',
  'Vietnam': 'vi-VN',
  'Argentina': 'es-AR',
  'Chile': 'es-CL',
  'Colombia': 'es-CO',
  'Peru': 'es-PE',
  'UAE': 'ar-AE',
  'Saudi Arabia': 'ar-SA',
  'Israel': 'he-IL',
  'Egypt': 'ar-EG',
  'Nigeria': 'en-NG',
  'Kenya': 'en-KE',
  'Pakistan': 'en-PK',
  'Bangladesh': 'bn-BD',
  'Sri Lanka': 'si-LK',
};

export const formatCurrency = (amount: number, country: string): string => {
  const currency = countryCurrencyMap[country] || 'USD';
  const locale = countryLocaleMap[country] || 'en-US';

  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency: currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
};

export const countries = Object.keys(countryCurrencyMap).sort();
